export const imgAuthorList = [
  "連臻",
  "★彡매실주 Maesil-ju",
  "SagoOishii",
  "SagoOishii",
  "sheep",
  "呆醬(Daichan)",
  "默翼(moyi)",
  "默翼(moyi)",
  "ONI",
  "MoYa",
  "玥晞(yueshi)",
  "玥晞(yueshi)",
  "摸摸(Momo)",
  "summerway",
  "柚子酒(yuzushu)",
  "MoYa",
  "Shimasen",
]